{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.135.7627.0 (24.08)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"foreign_investors\",\"order_flow_stat\",\"prices_history\",\"stock_ticker\",\"proprietary_trading\",\"foreign_investors (2)\",\"order_flow_stat (2)\",\"prices_history (2)\",\"proprietary_trading (2)\",\"stock_ticker (2)\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "35189449-6527-4593-b937-2e8316f90985",
        "fromColumn": "date",
        "fromTable": "foreign_investors (2)",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_9a0e1425-2aa0-4e41-a427-a7d1310e44c0"
      },
      {
        "name": "d5c32f9d-7743-4061-9b81-6235f435b607",
        "fromColumn": "date",
        "fromTable": "order_flow_stat (2)",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_bf314f38-56b8-423e-b467-c0fc3ae8240c"
      },
      {
        "name": "43cad437-ae75-4192-8cd4-8cee2e05d75b",
        "fromColumn": "date",
        "fromTable": "prices_history (2)",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c2b18bbc-5ca9-425b-8750-79d777c4ddbc"
      },
      {
        "name": "672a5605-da1a-4ac5-a61d-5c426e9d4cc4",
        "fromColumn": "date",
        "fromTable": "proprietary_trading (2)",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_8736b407-2184-499c-bc29-c4fddd24c456"
      },
      {
        "name": "AutoDetected_1b87facd-dee4-4add-afe6-e08c5451ccfa",
        "fromColumn": "ticker",
        "fromTable": "foreign_investors (2)",
        "toColumn": "ticker",
        "toTable": "stock_ticker (2)"
      },
      {
        "name": "AutoDetected_7458aaf7-aa3f-4793-83df-47665c164e3a",
        "fromColumn": "ticker",
        "fromTable": "order_flow_stat (2)",
        "toColumn": "ticker",
        "toTable": "stock_ticker (2)"
      },
      {
        "name": "AutoDetected_29fa8e73-6d48-457e-938b-c6089fa1f668",
        "fromColumn": "ticker",
        "fromTable": "prices_history (2)",
        "toColumn": "ticker",
        "toTable": "stock_ticker (2)"
      },
      {
        "name": "AutoDetected_1e0c991d-35dd-4dd7-8183-4b11b004f4b2",
        "fromColumn": "ticker",
        "fromTable": "proprietary_trading (2)",
        "toColumn": "ticker",
        "toTable": "stock_ticker (2)"
      },
      {
        "name": "49bdd47b-8d74-4b79-9d81-bc1b005b7834",
        "fromColumn": "date",
        "fromTable": "foreign_investors",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_dba0dbf1-cda2-4b38-9d19-cdc039cfd2ca"
      },
      {
        "name": "cc433cc8-2964-459f-b607-63252b014e6e",
        "fromColumn": "date",
        "fromTable": "order_flow_stat",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_4dfe500f-f83c-4d4f-a6d1-2e5f8e92c611"
      },
      {
        "name": "72b9d9bd-0229-462d-83a8-102398c76e12",
        "fromColumn": "date",
        "fromTable": "prices_history",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_d922454f-3f14-4aff-8602-5aca2b761478"
      },
      {
        "name": "a5142ddc-d6e4-4e12-845e-725d9a827b31",
        "fromColumn": "date",
        "fromTable": "proprietary_trading",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_aef835bb-4d91-4dbc-b599-3bde491a737b"
      },
      {
        "name": "AutoDetected_23041e22-7371-467d-9d64-4fc51399ee1f",
        "fromColumn": "ticker",
        "fromTable": "foreign_investors",
        "toColumn": "ticker",
        "toTable": "stock_ticker (2)"
      },
      {
        "name": "AutoDetected_ee24c07d-a5d0-4d3d-bd27-ebdf9958d1af",
        "fromColumn": "ticker",
        "fromTable": "order_flow_stat",
        "toColumn": "ticker",
        "toTable": "stock_ticker (2)"
      },
      {
        "name": "AutoDetected_b0078e43-ba9e-41f7-bceb-dcb9a4159eba",
        "fromColumn": "ticker",
        "fromTable": "prices_history",
        "toColumn": "ticker",
        "toTable": "stock_ticker (2)"
      },
      {
        "name": "AutoDetected_b6ee5f44-621c-41dd-8d25-154cbafd39c6",
        "fromColumn": "ticker",
        "fromTable": "proprietary_trading",
        "toColumn": "ticker",
        "toTable": "stock_ticker (2)"
      },
      {
        "name": "AutoDetected_e18c89c2-b34e-4303-9c69-f91696f9612e",
        "fromColumn": "ticker",
        "fromTable": "foreign_investors (2)",
        "toColumn": "ticker",
        "toTable": "stock_ticker"
      },
      {
        "name": "AutoDetected_4bbd43b2-22e6-4319-8a58-acbb41efd605",
        "fromColumn": "ticker",
        "fromTable": "order_flow_stat (2)",
        "toColumn": "ticker",
        "toTable": "stock_ticker"
      },
      {
        "name": "AutoDetected_cca97bd5-7b12-4702-a86d-3c1f2dd1ed73",
        "fromColumn": "ticker",
        "fromTable": "prices_history (2)",
        "toColumn": "ticker",
        "toTable": "stock_ticker"
      },
      {
        "name": "AutoDetected_461b0fe5-88fd-4562-8f83-8732b8ef2f99",
        "fromColumn": "ticker",
        "fromTable": "proprietary_trading (2)",
        "toColumn": "ticker",
        "toTable": "stock_ticker"
      },
      {
        "name": "AutoDetected_fd07de59-570f-4a82-8e3f-902a66976303",
        "fromColumn": "ticker",
        "fromTable": "foreign_investors",
        "toColumn": "ticker",
        "toTable": "stock_ticker"
      },
      {
        "name": "AutoDetected_b68f9817-8f19-46e4-9ee2-e745c2a35faf",
        "fromColumn": "ticker",
        "fromTable": "order_flow_stat",
        "toColumn": "ticker",
        "toTable": "stock_ticker"
      },
      {
        "name": "AutoDetected_adc4f400-5b43-452e-910e-c69ebf1150f6",
        "fromColumn": "ticker",
        "fromTable": "prices_history",
        "toColumn": "ticker",
        "toTable": "stock_ticker"
      },
      {
        "name": "AutoDetected_964a42b3-4b2f-4703-8025-f937ddaf7de5",
        "fromColumn": "ticker",
        "fromTable": "proprietary_trading",
        "toColumn": "ticker",
        "toTable": "stock_ticker"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_74622d56-6376-41d8-bab7-074d731c688e",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e178ca92-6510-4997-90d0-84294998a8d1",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "7d8eb983-ac33-4f0f-bdca-bddfaa5c58a5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "1c267d0a-0432-4e86-9f3e-146b5c3ac9f5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "f2b2f94d-74bb-442c-861b-f70a32da921a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "6c3de85d-cce0-4746-a246-efff8f133e16",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "5cba6791-b977-4007-a9b3-e89135c834d9",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "a4f20102-9f43-4f7d-bf17-3fa08011701f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4966b787-25eb-4efa-a326-483753f41162",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "2b3346ab-f58a-45db-b970-6c17389a7f6c",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "89a0ed85-9091-41e5-a3dc-cc73a1d47e29",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "1dd9b1fd-ffe6-4043-9345-28686a8a54e3",
                "ordinal": 3
              }
            ],
            "lineageTag": "206b8237-07f3-41ae-b64c-57c054c495bc"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "1cb30578-2351-492f-ab4f-2db22487d82d",
        "partitions": [
          {
            "name": "DateTableTemplate_74622d56-6376-41d8-bab7-074d731c688e",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "foreign_investors (2)",
        "columns": [
          {
            "name": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "181a4141-cc92-46a7-87a2-1a4633ce6a8a",
            "sourceColumn": "date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_9a0e1425-2aa0-4e41-a427-a7d1310e44c0"
                },
                "isDefault": true,
                "relationship": "35189449-6527-4593-b937-2e8316f90985"
              }
            ]
          },
          {
            "name": "net_trading_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "80e2d65d-6637-48f0-b682-92ebd1b6053a",
            "sourceColumn": "net_trading_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "net_trading_value_billion_vnd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d854039d-ff05-4c3f-b6d9-b56944acab55",
            "sourceColumn": "net_trading_value_billion_vnd",
            "summarizeBy": "sum"
          },
          {
            "name": "buy_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7fc0dd12-795a-4c1e-9ae2-ca6b52a8872d",
            "sourceColumn": "buy_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "buy_value_billion_vnd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "db44edcf-8ea9-498c-b1e4-d229eceed8b8",
            "sourceColumn": "buy_value_billion_vnd",
            "summarizeBy": "sum"
          },
          {
            "name": "sell_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "804bf27a-0d56-442c-9628-749ffa3b5f0e",
            "sourceColumn": "sell_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "sell_value_billion_vnd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3f6c5cfe-3c65-4be1-b25b-ea881ac8df4e",
            "sourceColumn": "sell_value_billion_vnd",
            "summarizeBy": "sum"
          },
          {
            "name": "remaining_room",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bc9d5864-09bd-4d36-bf6d-ee8393b47a31",
            "sourceColumn": "remaining_room",
            "summarizeBy": "sum"
          },
          {
            "name": "current_ownership",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4e5f684d-06ee-47cd-a345-3202e23edd26",
            "sourceColumn": "current_ownership",
            "summarizeBy": "sum"
          },
          {
            "name": "ticker",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dad2606e-3359-4fa1-b6ba-c9638ee64845",
            "sourceColumn": "ticker",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "449f09be-aab7-49ad-8ef3-d04b057ba076",
        "partitions": [
          {
            "name": "foreign_investors (2)",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Odbc.DataSource(\"database=F:\\2024\\Web_Scraping_and_Trade_Market_Analysis\\stock_market.db;dsn=SQLite3 Datasource\", [HierarchicalNavigation=true]),",
                "    foreign_investors_Table = Source{[Name=\"foreign_investors\",Kind=\"Table\"]}[Data]",
                "in",
                "    foreign_investors_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_9a0e1425-2aa0-4e41-a427-a7d1310e44c0",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "be9828a1-7b9f-4cfc-8270-75046f642194",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "be2cdddd-e0f6-45f2-b2d5-6b8a842b591a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "c3bcab01-b4ff-4d16-9825-bb48b364b58a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "757ec116-4431-4035-9fa3-4377358df18c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "0082a536-dea1-4b73-bd6c-dbdcf591a009",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "b10a28c4-ef2f-47c1-9dcd-6d35344b7505",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "b4e05c73-ef7e-4f1e-b480-84b13058013a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "079d2bf6-0e21-49cb-a81f-2c1f73d17387",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "074f9b46-1fe4-4d90-910c-9bab3cf89642",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "051055d1-a67b-4ff5-9cb4-12b502b79098",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "49eb54ab-4f8e-4d03-b4f2-b8eea3a36e98",
                "ordinal": 3
              }
            ],
            "lineageTag": "aec8dcf0-3648-4d0e-a866-6cd68f56d709"
          }
        ],
        "isHidden": true,
        "lineageTag": "f265ffbb-4d4b-48cf-9d06-ca94a314aad3",
        "partitions": [
          {
            "name": "LocalDateTable_9a0e1425-2aa0-4e41-a427-a7d1310e44c0",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('foreign_investors (2)'[date])), 1, 1), Date(Year(MAX('foreign_investors (2)'[date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "order_flow_stat (2)",
        "columns": [
          {
            "name": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "92339d56-3cf0-4d83-9fa3-99faa5e3e936",
            "sourceColumn": "date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_bf314f38-56b8-423e-b467-c0fc3ae8240c"
                },
                "isDefault": true,
                "relationship": "d5c32f9d-7743-4061-9b81-6235f435b607"
              }
            ]
          },
          {
            "name": "buy_orders",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "153885e1-192f-4bb3-b75a-0e93f2d7e497",
            "sourceColumn": "buy_orders",
            "summarizeBy": "sum"
          },
          {
            "name": "buy_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a356267d-1149-4118-914b-bdd759445b52",
            "sourceColumn": "buy_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "average_buy_order_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0aa5a9da-25ed-4d4f-ae86-ef9bcea278a1",
            "sourceColumn": "average_buy_order_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "sell_orders",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c760e9d0-cfe2-4b61-9077-e7160dcf07b7",
            "sourceColumn": "sell_orders",
            "summarizeBy": "sum"
          },
          {
            "name": "sell_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "738c5341-1a4c-48ea-b375-d614ec8160b3",
            "sourceColumn": "sell_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "average_sell_order_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c2e87c2a-6acb-4c04-9e05-689459319c93",
            "sourceColumn": "average_sell_order_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "net_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ccc917ca-533a-4a5b-bb35-0d0dbd71792c",
            "sourceColumn": "net_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "ticker",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b36ce88-d116-4cd4-947a-03f272e67fa4",
            "sourceColumn": "ticker",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f25e29e0-54ce-48b2-9034-d99445c63f70",
        "partitions": [
          {
            "name": "order_flow_stat (2)",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Odbc.DataSource(\"database=F:\\2024\\Web_Scraping_and_Trade_Market_Analysis\\stock_market.db;dsn=SQLite3 Datasource\", [HierarchicalNavigation=true]),",
                "    order_flow_stat_Table = Source{[Name=\"order_flow_stat\",Kind=\"Table\"]}[Data]",
                "in",
                "    order_flow_stat_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_bf314f38-56b8-423e-b467-c0fc3ae8240c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "246da8e9-2aeb-457d-a22e-b3fc03dc30b9",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "d151771f-776b-44ce-8d32-dd24c7c41e40",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "faf2fade-ca33-4c06-9343-4853fcf69b17",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "17409ae9-02b7-4bd3-8ddb-e926bdfc25d0",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "45105ebd-3379-4829-9533-fa0731a8c7e1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "714f34db-71ee-43cd-85de-e260d2d3e60c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "3e3ecc1c-ff79-4416-a60b-f84c27107fc1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "9db0c05b-02ed-472f-8982-df03dfe3ea38",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "9ecfe188-10f6-4fb5-bff9-89786b54fcce",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "8a08065c-d6a4-4bc3-b1a7-5e007638f2fb",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f5d9ff01-b5ed-4092-8af6-e271993c8dc7",
                "ordinal": 3
              }
            ],
            "lineageTag": "07ee885e-3f12-4772-b3f4-1f47a1a7a7d0"
          }
        ],
        "isHidden": true,
        "lineageTag": "79f1b495-0346-4bbb-8957-93c12a8e9d99",
        "partitions": [
          {
            "name": "LocalDateTable_bf314f38-56b8-423e-b467-c0fc3ae8240c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('order_flow_stat (2)'[date])), 1, 1), Date(Year(MAX('order_flow_stat (2)'[date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "prices_history (2)",
        "columns": [
          {
            "name": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e585d1a2-ec34-43f6-a9db-8b9b98d9e01a",
            "sourceColumn": "date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c2b18bbc-5ca9-425b-8750-79d777c4ddbc"
                },
                "isDefault": true,
                "relationship": "43cad437-ae75-4192-8cd4-8cee2e05d75b"
              }
            ]
          },
          {
            "name": "close",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1701ff05-8ab0-49a2-a627-1b407ddaff8b",
            "sourceColumn": "close",
            "summarizeBy": "sum"
          },
          {
            "name": "adjusting_price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9e618616-3f43-449e-95c6-3872670f6c17",
            "sourceColumn": "adjusting_price",
            "summarizeBy": "sum"
          },
          {
            "name": "rate_change",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "87bea3a9-aaa8-427d-9a61-0b2de0f56f75",
            "sourceColumn": "rate_change",
            "summarizeBy": "sum"
          },
          {
            "name": "order_matching_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "53b072a5-965b-4c1c-9f77-bac4cfe5bfa8",
            "sourceColumn": "order_matching_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "order_matching_value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a41898d0-5b11-46dd-861f-5a1ddf7604e1",
            "sourceColumn": "order_matching_value",
            "summarizeBy": "sum"
          },
          {
            "name": "block_trade_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ba5b0ac1-54f2-4054-965f-8ba937f6c4cd",
            "sourceColumn": "block_trade_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "block_trade_value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "900c5fa0-3e08-4d56-9009-44a50042e6d8",
            "sourceColumn": "block_trade_value",
            "summarizeBy": "sum"
          },
          {
            "name": "open",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b389dd4e-ca6d-441d-a21a-a5448cd7a210",
            "sourceColumn": "open",
            "summarizeBy": "sum"
          },
          {
            "name": "high",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f7d40868-21e9-4341-afd7-c0b15c1d2401",
            "sourceColumn": "high",
            "summarizeBy": "sum"
          },
          {
            "name": "low",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9cb6bed7-eefd-4a6f-bbee-1e9a1c4f3ea3",
            "sourceColumn": "low",
            "summarizeBy": "sum"
          },
          {
            "name": "ticker",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c3ecb446-6fa8-4623-aa0b-3b1282f77804",
            "sourceColumn": "ticker",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3d0dcaf6-6f7a-40d3-9e5f-f63d27155cd3",
        "partitions": [
          {
            "name": "prices_history (2)",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Odbc.DataSource(\"database=F:\\2024\\Web_Scraping_and_Trade_Market_Analysis\\stock_market.db;dsn=SQLite3 Datasource\", [HierarchicalNavigation=true]),",
                "    prices_history_Table = Source{[Name=\"prices_history\",Kind=\"Table\"]}[Data]",
                "in",
                "    prices_history_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_c2b18bbc-5ca9-425b-8750-79d777c4ddbc",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9dcbc2d5-2bff-40d2-be06-572b04c10191",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "66438937-7d2f-4226-9677-c80e487494ff",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "a94ab436-d82a-460a-87cb-7c54114c9c87",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "247a5251-23bb-4a60-a45b-e46747d38b37",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "85988206-1ea2-4585-824b-deb72b753385",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "a66823c1-99b4-4972-9693-5376564d9dec",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "345dac83-e087-49b3-86ec-b66343076076",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "8274adc0-9e56-49e8-82be-4192574cf9a0",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "1339cef3-be01-4fed-a3cc-252946b98bf6",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "f0ce2f04-4230-404e-9b79-3e056cd2b299",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "4206db90-eb77-47d4-aa38-9fd69596a6d2",
                "ordinal": 3
              }
            ],
            "lineageTag": "38273baa-cd64-4299-a348-77112a37d630"
          }
        ],
        "isHidden": true,
        "lineageTag": "e94a8332-9e4c-49fa-99d8-dcd7dbb05f44",
        "partitions": [
          {
            "name": "LocalDateTable_c2b18bbc-5ca9-425b-8750-79d777c4ddbc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('prices_history (2)'[date])), 1, 1), Date(Year(MAX('prices_history (2)'[date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "proprietary_trading (2)",
        "columns": [
          {
            "name": "ticker",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bee2b193-9f04-4c92-ae97-12a6e06c9edc",
            "sourceColumn": "ticker",
            "summarizeBy": "none"
          },
          {
            "name": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "aa8221f0-19e9-414e-baba-a4c5a6cff6bd",
            "sourceColumn": "date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_8736b407-2184-499c-bc29-c4fddd24c456"
                },
                "isDefault": true,
                "relationship": "672a5605-da1a-4ac5-a61d-5c426e9d4cc4"
              }
            ]
          },
          {
            "name": "buy_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fb23e170-f579-4f39-aa65-1cd167972ed0",
            "sourceColumn": "buy_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "buy_value_bil_vnd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "882393bd-2087-45a9-ac4d-73b6b49d2f72",
            "sourceColumn": "buy_value_bil_vnd",
            "summarizeBy": "sum"
          },
          {
            "name": "sell_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "857a4e07-a75b-4758-9c82-f24e08bef9f2",
            "sourceColumn": "sell_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "sell_value_bil_vnd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9ac901ec-8efc-4f7e-87c1-b920c173799f",
            "sourceColumn": "sell_value_bil_vnd",
            "summarizeBy": "sum"
          },
          {
            "name": "net_trading_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7a6d1338-fc18-408a-a23b-f28882ea8c3d",
            "sourceColumn": "net_trading_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "net_trading_value_bil_vnd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ae07bb88-f312-4c24-8ffe-8d76307100d8",
            "sourceColumn": "net_trading_value_bil_vnd",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "c6362cfc-a013-4bb9-b825-d6b456cefea5",
        "partitions": [
          {
            "name": "proprietary_trading (2)",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Odbc.DataSource(\"database=F:\\2024\\Web_Scraping_and_Trade_Market_Analysis\\stock_market.db;dsn=SQLite3 Datasource\", [HierarchicalNavigation=true]),",
                "    proprietary_trading_Table = Source{[Name=\"proprietary_trading\",Kind=\"Table\"]}[Data]",
                "in",
                "    proprietary_trading_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_8736b407-2184-499c-bc29-c4fddd24c456",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "220b8716-b429-4ef7-a430-f526ca076ca5",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "92a406c2-86ba-4bee-b189-e485edb8baa5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "578a31c8-0e07-494a-bcdb-06505f13f021",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ae2269b0-ce89-4168-a477-164c7c8349e1",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "a426a976-5b8a-4ea8-8e86-53db2621599e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "7fdd6898-fc19-4d2b-8a00-481e99d63cad",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "0f21d2a2-c4c6-4323-beb1-12e642f2c557",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "374bcfff-de47-42f2-9451-d4a2ff081281",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "089922c8-6177-4165-a259-77e827fa1bc1",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d5be84ad-769d-4897-871f-3a158dc0de24",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b27c8d61-e083-4d97-a38f-a4aabc5617b9",
                "ordinal": 3
              }
            ],
            "lineageTag": "1f7ffaf9-e57e-4469-beb3-8f75da5d0104"
          }
        ],
        "isHidden": true,
        "lineageTag": "34ff4480-8c45-43a6-9702-70579c4e8897",
        "partitions": [
          {
            "name": "LocalDateTable_8736b407-2184-499c-bc29-c4fddd24c456",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('proprietary_trading (2)'[date])), 1, 1), Date(Year(MAX('proprietary_trading (2)'[date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "stock_ticker (2)",
        "columns": [
          {
            "name": "ticker",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d36ae082-2bba-44de-9f38-1662d89785e2",
            "sourceColumn": "ticker",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0e4115c1-9e5e-48ba-b8c7-ebe026f9fe2a",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "platform",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "568d6616-18d1-43cd-9acf-80d05e622393",
            "sourceColumn": "platform",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "39d25c60-b125-43bb-a9d7-f0871a0e9fef",
        "partitions": [
          {
            "name": "stock_ticker (2)",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Odbc.DataSource(\"database=F:\\2024\\Web_Scraping_and_Trade_Market_Analysis\\stock_market.db;dsn=SQLite3 Datasource\", [HierarchicalNavigation=true]),",
                "    stock_ticker_Table = Source{[Name=\"stock_ticker\",Kind=\"Table\"]}[Data]",
                "in",
                "    stock_ticker_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "foreign_investors",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1566c90a-4820-4167-974b-b4c99dffbd0c",
            "sourceColumn": "date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_dba0dbf1-cda2-4b38-9d19-cdc039cfd2ca"
                },
                "isDefault": true,
                "relationship": "49bdd47b-8d74-4b79-9d81-bc1b005b7834"
              }
            ]
          },
          {
            "name": "net_trading_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c0b5e163-cff7-424e-aca4-6c584f8cf807",
            "sourceColumn": "net_trading_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "net_trading_value_billion_vnd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c9c00d69-93e2-4d3c-a9db-6246c62a2244",
            "sourceColumn": "net_trading_value_billion_vnd",
            "summarizeBy": "sum"
          },
          {
            "name": "buy_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e63b34f1-08d7-4bcd-84fd-63d3d274da85",
            "sourceColumn": "buy_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "buy_value_billion_vnd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "024ffd71-bb14-4723-a78a-ec8896fa4139",
            "sourceColumn": "buy_value_billion_vnd",
            "summarizeBy": "sum"
          },
          {
            "name": "sell_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "459a7631-973d-4798-b30e-4a7283f23165",
            "sourceColumn": "sell_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "sell_value_billion_vnd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "71b89cdf-d94e-4569-aab4-e43e7a233439",
            "sourceColumn": "sell_value_billion_vnd",
            "summarizeBy": "sum"
          },
          {
            "name": "remaining_room",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d69b657d-e711-416a-8e0d-2d06fff5d4fd",
            "sourceColumn": "remaining_room",
            "summarizeBy": "sum"
          },
          {
            "name": "current_ownership",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a4303c3f-1dce-4f4c-9a4b-7774d60c78aa",
            "sourceColumn": "current_ownership",
            "summarizeBy": "sum"
          },
          {
            "name": "ticker",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b1e0fc1f-97cd-402d-96a1-8cd0c719bb0a",
            "sourceColumn": "ticker",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c8e8c352-3fa4-4a93-a3bf-7a64faf1f7ff",
        "partitions": [
          {
            "name": "foreign_investors",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Odbc.DataSource(\"database=F:\\2024\\Web_Scraping_and_Trade_Market_Analysis\\stock_market.db;dsn=SQLite3 Datasource\", [HierarchicalNavigation=true]),",
                "    foreign_investors_Table = Source{[Name=\"foreign_investors\",Kind=\"Table\"]}[Data]",
                "in",
                "    foreign_investors_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_dba0dbf1-cda2-4b38-9d19-cdc039cfd2ca",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "36685eba-1184-4b16-9966-bb2e15acd6a0",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "baf1ddf7-cab7-4b11-b1e7-770e8ac92c9d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "78985804-a40e-4db2-82f1-b16be4bf44f7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "c51a3d01-0e01-4b5b-8d52-04b39c732a87",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "5aff479b-eaf5-4bd1-b980-90f54edaeffa",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "ea260f37-4bac-4f74-8511-4e6484efe5ad",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "422abcac-a3b3-4db8-9d68-85a0111befe7",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "e861cc6e-c099-4c04-95e1-0af7bb3407a3",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "364b530e-c0f7-42f9-92b0-f9f991c7fa42",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "bf771c31-be09-47f8-bafb-da8faf09cc4f",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "3c9986ef-868c-4379-8944-30e868f31504",
                "ordinal": 3
              }
            ],
            "lineageTag": "84f87300-ceed-4cd5-b853-0aeb9e798602"
          }
        ],
        "isHidden": true,
        "lineageTag": "45ac2204-c548-4a1c-8d3d-b6547ddc0a44",
        "partitions": [
          {
            "name": "LocalDateTable_dba0dbf1-cda2-4b38-9d19-cdc039cfd2ca",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('foreign_investors'[date])), 1, 1), Date(Year(MAX('foreign_investors'[date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "order_flow_stat",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1a1022cf-f59d-4862-ba40-91daa334f9c8",
            "sourceColumn": "date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_4dfe500f-f83c-4d4f-a6d1-2e5f8e92c611"
                },
                "isDefault": true,
                "relationship": "cc433cc8-2964-459f-b607-63252b014e6e"
              }
            ]
          },
          {
            "name": "buy_orders",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9740284d-5053-4d24-87bf-15163bedbb32",
            "sourceColumn": "buy_orders",
            "summarizeBy": "sum"
          },
          {
            "name": "buy_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "848617c6-7956-4783-b841-97219beabf21",
            "sourceColumn": "buy_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "average_buy_order_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5bc53959-fc26-4afd-b0fd-c80173404698",
            "sourceColumn": "average_buy_order_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "sell_orders",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b7c3732d-8af8-4efe-a5de-12a34188882c",
            "sourceColumn": "sell_orders",
            "summarizeBy": "sum"
          },
          {
            "name": "sell_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1a3ca134-f69c-41ee-9abe-c58a4d529080",
            "sourceColumn": "sell_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "average_sell_order_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fe3a6324-6ee7-421d-8bfd-1dc5e0814c11",
            "sourceColumn": "average_sell_order_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "net_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7c44afef-f6ca-4583-852e-20e7dd876e50",
            "sourceColumn": "net_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "ticker",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "05ea67c5-7107-4d27-8e10-5bf37b1cddf5",
            "sourceColumn": "ticker",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "226f2d95-42ae-47bd-8a43-1abc7338ce3b",
        "partitions": [
          {
            "name": "order_flow_stat",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Odbc.DataSource(\"database=F:\\2024\\Web_Scraping_and_Trade_Market_Analysis\\stock_market.db;dsn=SQLite3 Datasource\", [HierarchicalNavigation=true]),",
                "    order_flow_stat_Table = Source{[Name=\"order_flow_stat\",Kind=\"Table\"]}[Data]",
                "in",
                "    order_flow_stat_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_4dfe500f-f83c-4d4f-a6d1-2e5f8e92c611",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "340bf1a6-4b97-4517-9da3-56b518b7a83a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "b9dbbc90-5e96-44d0-afa2-8cf8438639bf",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "c9cb7141-815b-4179-b662-e75c62048297",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "93f4183a-6906-4c40-8c9b-4f8513ce6af8",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "8bb4d841-fa1d-4bda-bc1a-cac9285f794a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "41ea3847-afc7-4d73-8212-9bfb63ce099e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "1548b462-1b24-490b-b80e-3e80d4ef52f2",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "d05cc48a-2afb-45d4-ac3c-f998553d4aa5",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "4da67645-c181-4a0b-bd4c-c7512d5d53d2",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "79152956-f40d-4938-b8cb-d75b09ffe9a6",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "1814b4cc-73bd-400a-a689-9298d296ea61",
                "ordinal": 3
              }
            ],
            "lineageTag": "7ae3f9ad-231c-4551-870e-47214ed3166f"
          }
        ],
        "isHidden": true,
        "lineageTag": "0f8b5565-3ba0-44f7-a597-9b59c0839baf",
        "partitions": [
          {
            "name": "LocalDateTable_4dfe500f-f83c-4d4f-a6d1-2e5f8e92c611",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('order_flow_stat'[date])), 1, 1), Date(Year(MAX('order_flow_stat'[date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "prices_history",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "abfda402-f037-46bb-b7e6-3880eb5acb27",
            "sourceColumn": "date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_d922454f-3f14-4aff-8602-5aca2b761478"
                },
                "isDefault": true,
                "relationship": "72b9d9bd-0229-462d-83a8-102398c76e12"
              }
            ]
          },
          {
            "name": "close",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6e6dc653-14d7-4950-9099-42cd31df0bb4",
            "sourceColumn": "close",
            "summarizeBy": "sum"
          },
          {
            "name": "adjusting_price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d044ca7a-d4d9-4a20-bde2-8a13bf9cd4e7",
            "sourceColumn": "adjusting_price",
            "summarizeBy": "sum"
          },
          {
            "name": "rate_change",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2636fdb7-07d1-40a5-a357-8cbb3d9d32bf",
            "sourceColumn": "rate_change",
            "summarizeBy": "sum"
          },
          {
            "name": "order_matching_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c1f83994-1316-423e-972b-4e846e6c4375",
            "sourceColumn": "order_matching_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "order_matching_value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "19bb6bc6-0399-405c-906e-fc993ea93e0a",
            "sourceColumn": "order_matching_value",
            "summarizeBy": "sum"
          },
          {
            "name": "block_trade_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3b028e95-a353-4c5b-a81e-4f616d19e7f3",
            "sourceColumn": "block_trade_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "block_trade_value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "79eab6be-94fa-44b1-9617-e16982e5cb1b",
            "sourceColumn": "block_trade_value",
            "summarizeBy": "sum"
          },
          {
            "name": "open",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bd4f2dd1-9897-42c3-b211-dc78569e1759",
            "sourceColumn": "open",
            "summarizeBy": "sum"
          },
          {
            "name": "high",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f51ccaf4-c15e-4db5-a483-53ab6a3a7957",
            "sourceColumn": "high",
            "summarizeBy": "sum"
          },
          {
            "name": "low",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "05566f99-91d4-4620-91f4-bdc822a59601",
            "sourceColumn": "low",
            "summarizeBy": "sum"
          },
          {
            "name": "ticker",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bfffefc4-34ba-49c7-ab02-a72f8a018c25",
            "sourceColumn": "ticker",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "86049276-1773-475a-adf3-5e79fd55bfa7",
        "partitions": [
          {
            "name": "prices_history",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Odbc.DataSource(\"database=F:\\2024\\Web_Scraping_and_Trade_Market_Analysis\\stock_market.db;dsn=SQLite3 Datasource\", [HierarchicalNavigation=true]),",
                "    prices_history_Table = Source{[Name=\"prices_history\",Kind=\"Table\"]}[Data]",
                "in",
                "    prices_history_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_d922454f-3f14-4aff-8602-5aca2b761478",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "30c3267d-610f-4048-b319-88b17a0bb3da",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "ba4e59a5-f6f9-4b27-b2a3-6b3b82a826fc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "1eee8d2b-796c-4a84-a35b-0b23a0e13dc2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "787da195-4014-43fb-8c30-8dd281d0c52a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "87ae695a-1b41-4922-8326-2bd3ff346afd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "dcd307a2-fb39-4605-8d46-8b1a4436603c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "bc707903-03c2-4846-a6e7-fe243da47f33",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "cb5bd585-6da5-4132-8df5-a36d92d2bc2d",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a7fab13c-6c44-470c-a978-f931fae21aea",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "49b23d49-8a3b-4862-8869-959f4aa5b117",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "686724da-ddb2-47c7-87ba-6782bd4731fb",
                "ordinal": 3
              }
            ],
            "lineageTag": "76435503-010b-46a3-bd37-d83f49ee4cb1"
          }
        ],
        "isHidden": true,
        "lineageTag": "eead9f9e-a011-42e2-889e-83c407bb0f76",
        "partitions": [
          {
            "name": "LocalDateTable_d922454f-3f14-4aff-8602-5aca2b761478",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('prices_history'[date])), 1, 1), Date(Year(MAX('prices_history'[date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "stock_ticker",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ticker",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4c917200-b3e0-4ba6-9cbf-91a55b4249d8",
            "sourceColumn": "ticker",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ef4c626a-ccb9-47e9-b271-1d3075395f88",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "platform",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c12c1c5f-2c89-4802-9cdc-68b63dc71a13",
            "sourceColumn": "platform",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f49027ae-905c-4af3-a42d-1a586ae3ac56",
        "partitions": [
          {
            "name": "stock_ticker",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Odbc.DataSource(\"database=F:\\2024\\Web_Scraping_and_Trade_Market_Analysis\\stock_market.db;dsn=SQLite3 Datasource\", [HierarchicalNavigation=true]),",
                "    stock_ticker_Table = Source{[Name=\"stock_ticker\",Kind=\"Table\"]}[Data]",
                "in",
                "    stock_ticker_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "proprietary_trading",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ticker",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a56e49a4-78f1-4a1b-85f7-9c07406e072b",
            "sourceColumn": "ticker",
            "summarizeBy": "none"
          },
          {
            "name": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "74701c3b-52f0-432a-9d2c-00fe66478b5e",
            "sourceColumn": "date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_aef835bb-4d91-4dbc-b599-3bde491a737b"
                },
                "isDefault": true,
                "relationship": "a5142ddc-d6e4-4e12-845e-725d9a827b31"
              }
            ]
          },
          {
            "name": "buy_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4091bb53-56df-4f0d-9535-a1e0f074d5bf",
            "sourceColumn": "buy_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "buy_value_bil_vnd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a7e3e02a-65d8-4e3c-88ca-0e9d1c46aa67",
            "sourceColumn": "buy_value_bil_vnd",
            "summarizeBy": "sum"
          },
          {
            "name": "sell_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5e7671c6-4376-4c6d-b8dc-23aa8f66fc78",
            "sourceColumn": "sell_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "sell_value_bil_vnd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2700871b-9332-4d80-983a-813d6890b07d",
            "sourceColumn": "sell_value_bil_vnd",
            "summarizeBy": "sum"
          },
          {
            "name": "net_trading_volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e74bead5-c2f9-493e-8717-5c808f36844c",
            "sourceColumn": "net_trading_volume",
            "summarizeBy": "sum"
          },
          {
            "name": "net_trading_value_bil_vnd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "28216d6a-0f62-4e81-bd01-b80b51ad0d40",
            "sourceColumn": "net_trading_value_bil_vnd",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "3f5e3536-5cae-4476-aea0-d916e1ac1049",
        "partitions": [
          {
            "name": "proprietary_trading",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Odbc.DataSource(\"database=F:\\2024\\Web_Scraping_and_Trade_Market_Analysis\\stock_market.db;dsn=SQLite3 Datasource\", [HierarchicalNavigation=true]),",
                "    proprietary_trading_Table = Source{[Name=\"proprietary_trading\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(proprietary_trading_Table,{\"stock_ticker\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_aef835bb-4d91-4dbc-b599-3bde491a737b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b03710e2-fd2b-4b4d-94d0-a1c4593268d5",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "584125a5-7a5b-4837-84db-cb563ea50024",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "e74adc1a-f3c6-4cbc-b7e5-a747073924ed",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "866365c0-ec3b-4b12-b933-a63505418507",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "c3b13770-2090-4ee6-a1fd-278ef667f12a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "3ae39eb9-0c93-42ba-a1a7-bc745c9947d3",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "18cf06f8-bd16-41b3-9edb-07fe415c6f53",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "789f1fd0-2b52-44e6-bf07-57bff4cae700",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "4cac961c-b3c6-4fa9-8c98-2e38857b4e84",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b0512c4f-503a-42b8-8606-a6642dace58b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "8faf8e2c-26a3-4856-ac8a-e45421284734",
                "ordinal": 3
              }
            ],
            "lineageTag": "444ea601-3911-4750-b8ce-cfcadc1d62ec"
          }
        ],
        "isHidden": true,
        "lineageTag": "07df90b3-2eb7-4d63-bb1a-6ccaa6bfd9c5",
        "partitions": [
          {
            "name": "LocalDateTable_aef835bb-4d91-4dbc-b599-3bde491a737b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('proprietary_trading'[date])), 1, 1), Date(Year(MAX('proprietary_trading'[date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}